### PR TITLE
Strict json

### LINKED ISSUE #22: add a strict mode: throw when json-body is non-object
[rfc4627](https://www.ietf.org/rfc/rfc4627.txt)
also see https://github.com/koajs/bodyparser/issues/19#issuecomment-98367747.

### PR DESCRIPTION
**Pull request by dead-horse**
closes #22

### CODE REVIEW

**Comment by fengmk2** [comment]
Error message change to "invalid JSON object or array" will be better.

**Comment by dead-horse** [comment]
@fengmk2  fixed

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
+ co-body@2.0.0

**Pull request merged**
