### PR TITLE
qs dependency update

### PR DESCRIPTION
**Pull request by dehbmarques**
There's some fixes in the latest version

### CODE REVIEW

**Comment by winsonwq** [comment]
related to #16

**Comment by zhoul-HS** [comment]
[co-better-body](https://github.com/zhoul-HS/co-better-body) if you want. also on [npm](https://npmjs.org/packages/co-better-body)

**Comment by winsonwq** [comment]
@zhoul-HS Thanks.

**Comment by fengmk2** [comment]
Fixes on 05efbe03aa25e324148d77176a6d6aa8b26ffa1d

**Pull request closed without merging**
