### PR TITLE
Add a parameter named transformBody to parse the request body in a user-defined way

### PR DESCRIPTION
**Pull request by mstar-kk**
Add a parameter named transformBody to parse the request body in a user-defined way. For example,
```
//opts
const opts = {
    transformBody: function(str) {
        const JsonBigInt = require("json-bigint");
        return JsonBigInt.parse(str);
    }
}
```

### CODE REVIEW

**Comment by dead-horse** [comment]
we should separate the transform function for three types

**Comment by dead-horse** [comment]
I don't think add this options is required. If you have something that is not compatible with the standard， you should use https://github.com/stream-utils/raw-body to handle it by yourself.

Another solution is use `text` type and parse by yourself later.

**Comment by mstar-kk** [comment]
I think that as long as node provides services to the outside, this problem can not be avoided, because there is no guarantee of what language the client is java，python or whatever. And just like parse form body can use different querystring module in a user-defined, this paramater do the same job for other body type. Axios has interceptors with similar capabilities. From this point of view, this function is required. 
Thanks for review my code.

@dead-horse

**Comment by dead-horse** [comment]
Whatever language the client use, they should follow the spec (like https://www.json.org/json-en.html, https://url.spec.whatwg.org/#urlencoded-serializing), and co-body only support the standard version of JSON / X-www-form-urlencoded format.

**Comment by dead-horse** [comment]
Certainly the phenomenon you describe exists, but there are so few scenarios that I don't want to have to provide new features for the sake of such scenarios, which is not conducive to keeping the code cohesive and streamlined!

**Comment by mstar-kk** [comment]
ok，I understand.And thanks again. @dead-horse

**Pull request closed without merging**
